name: Deploy infra
description: Deploy infra using terraform
inputs:
  environment:
    description: target environment
    required: true
  aws-statefile-s3-bucket:
    description: s3 bucket used to store state files
    required: true
  aws-region:
    description: region to deploy aws resources
    required: true

runs:
  using: "composite"
  steps:
    - name: Terraform Init
      shell: bash
      run: |
        cd infra && terraform init \
        -backend-config="bucket=${{ inputs.aws-statefile-s3-bucket }}" \
        -backend-config="key=${{ github.event.repository.name }}" \
        -backend-config="region=${{ inputs.aws-region }}"

    - name: Terraform Validate
      shell: bash
      run: terraform validate

    - name: Terraform Plan
      shell: bash
      id: terraform-plan
      run: cd infra &&
        terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
        terraform plan -var-file=./environments/${{ inputs.environment }}/terraform.tfvars -out="${{ inputs.environment }}.plan"

    - name: Terraform Apply
      shell: bash
      id: terraform-apply
      run: cd infra &&
        terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
        terraform apply "${{ inputs.environment }}.plan"
