name: "Deploy infra"

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws-region:
        type: string
        required: true
      aws-assume-role-arn:
        type: string
        required: true
      aws-statefile-s3-bucket:
        type: string
        required: true

jobs:
  infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: Github_to_AWS_via_FederatedOIC
          aws-region: ${{ inputs.aws-region }}

      - name: Terraform Init
        run: |
          cd infra && terraform init \
          -backend-config="bucket=${{ inputs.aws-statefile-s3-bucket }}" \
          -backend-config="key=${{ github.event.repository.name }}" \
          -backend-config="region=${{ inputs.aws-region }}"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: terraform-plan
        run: cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform plan -var-file=./environments/${{ inputs.environment }}/terraform.tfvars -out="${{ inputs.environment }}.plan"

      - name: Terraform Apply
        id: terraform-apply
        run: cd infra &&
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }} &&
          terraform apply "${{ inputs.environment }}.plan"
