name: "Deploy infra"

on:
  push:
    branches:
      - main
      - development
    paths:
      - "infra/**"
      - ".github/workflows/deploy-infra.yml"
      - ".github/actions/deploy/infra/action.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.3

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::430118847006:role/GithubActionsESSantanPipeline
          role-session-name: Github_to_AWS_via_FederatedOIC
          aws-region: "sa-east-1"

      - name: deploy dev
        if: ${{ github.ref == 'refs/heads/development' }}
        uses: ./.github/actions/deploy/infra
        with:
          environment: "development"
          aws-statefile-s3-bucket: essantana-sa-east-1-terraform-pipeline

      - name: deploy prod
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/deploy/infra
        with:
          environment: "production"
          aws-statefile-s3-bucket: essantana-sa-east-1-terraform-pipeline

