name: "Deploy Development"

on:
  push:
    branches:
      - main
      - development
    paths:
      - "infra/*"
      - ".github/workflows/deploy-infra.yml"
      - ".github/actions/deploy/infra/action.yml"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    runs-on: "ubuntu-latest"
    defaults:
      run:
        working-directory: "./github"
    steps:
      - name: deploy dev
        if: ${{ github.ref == 'refs/heads/development' }}
        uses: ./actions/deploy/infra
        with:
          environment: "development"
          aws-region: "sa-east-1"
          aws-assume-role-arn: arn:aws:iam::430118847006:role/GithubActionsESSantanPipeline
          aws-statefile-s3-bucket: essantana-sa-east-1-terraform-pipeline

      - name: deploy prod
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./actions/deploy/infra
        with:
          environment: "production"
          aws-region: "sa-east-1"
          aws-assume-role-arn: arn:aws:iam::430118847006:role/GithubActionsESSantanPipeline
          aws-statefile-s3-bucket: essantana-sa-east-1-terraform-pipeline
