name: "Deploy Development"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infra:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: "development"
      aws-region: "sa-east-1"
      aws-assume-role-arn: $AWS_ASSUME_ROLE_ARN
      aws-statefile-s3-bucket: $AWS_STATEFILE_S3_BUCKET
